import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import React from "react";

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserratAlternates.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}